"""empty message

Revision ID: e8e96ebc60c2
Revises: aaa4410895ea
Create Date: 2024-10-05 15:56:42.867752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e96ebc60c2'
down_revision: Union[str, None] = 'aaa4410895ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_category_name', 'categories', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_category_name', 'categories', type_='unique')
    # ### end Alembic commands ###
